CREATE TABLE IF NOT EXISTS name (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS rank (
    id INT PRIMARY KEY AUTO_INCREMENT,
    FOREIGN KEY (name_id) REFERENCES name(id)
    user_rank VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS chapter (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(30) NOT NULL
);